### ISSUE TITLE
[Feature request] Allow for mulitple *arr instance of the same type

### ISSUE THREAD

**Issue by lichenophile** [Vansmak/mediarr_sensor#10]
I have 2 sonarr and 2 radarr, the secondary of each is configured for anime specifically. So I am looking for the ability to add more than one... 

perhaps using something like a suffix on the entry that will be used for entitie naming, like follows? Though I'm not sure what the best convention to follow here would be

```
    sonarr:
      url: http://192.168.0.162
      api_key: !secret sonarr_api_key
      max_items: 20
      days_to_check: 60

    sonarr_anime:
      url: http://192.168.0.161
      api_key: !secret sonarr_api_key_anime
      max_items: 20
      days_to_check: 60
```

I suppose this would also need support from the media card too, let me know if I should open a request there also
