### ISSUE TITLE
Can't make this work

### ISSUE THREAD

**Issue by janaxhell** [Vansmak/mediarr_sensor#12]
I did post some time ago, but never made this to work, at best some posters for a day, then broken images, now it's completely empty.
This happens both from homeassistant.local and my cloudflare domain. All my *arrs are on server 192.168.1.94 while HA is on 192.168.1.193.
My YAML in configuration is

```
sensor:
  - platform: mediarr
    sonarr:  # Optional
      url: 192.168.1.94:8989
      api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      max_items: 10
      days_to_check: 60
    
    radarr:  # Optional
      url: 192.168.1.94:7878
      api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      max_items: 10
      days_to_check: 60 #breaking change

    seer: 
      url: 192.168.1.94:5055
      api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      max_items: 10
      tmdb_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
      trending: true # Optional     
      discover: true  # Optional
      popular_movies: true  # Optional
      popular_tv: true # Optional

    tmdb:  # Optional
      api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true          # Default endpoint
      now_playing: true       # Optional
      upcoming: true          # Optional
      on_air: true            # Optional
      airing_today: false     # Optional
      
    emby:  # Trying this in place of jellyfin
      url: 192.168.1.94:8096
      token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      max_items: 10
      tmdb_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
```
What I see in HA is this:

![Image](https://github.com/user-attachments/assets/4c8288f3-8fec-4b00-a396-aa145d58ef6c)

What's wrong?
