### ISSUE TITLE
Jellyseerr no Infos and posters

### ISSUE THREAD

**Issue by Stefan765** [Vansmak/mediarr_sensor#18]
Hello, unfortunately jellyseerr does not display any pictures or information. The sensors are created, but the status is only 1. Is there something wrong with the data I have entered? Best regards 
Stefan 

![Image](https://github.com/user-attachments/assets/14eeb1c2-fea7-4283-8688-92ab6a3c874f)
![Image](https://github.com/user-attachments/assets/85afe697-ce99-44bf-b6cf-885e470cce1a)

**Comment by Vansmak** [comment]
please download latest 3.1.3

**Comment by Stefan765** [comment]
I have updated to 3.1.3, but unfortunately the posters still do not appear.

**Comment by Vansmak** [comment]
Show the sensors attributes. 

Look in ha logs to see if errors.

**Comment by Stefan765** [comment]
In my home assistant log I permanently get this error message

 ERROR (MainThread) [custom_components.mediarr.common.tmdb_sensor] TMDB API error: 401 for URL: https://api.themoviedb.org/3/tv/278785?api_key=your_tmdb_api_key

**Comment by Vansmak** [comment]
Use the really long key for tmdb and try with quotes

**Comment by Stefan765** [comment]
Thanks, the sensors are now working, but media requests are still empty.

**Comment by Vansmak** [comment]
And what does the seer sensor attributes show? Any logs?

**Comment by Stefan765** [comment]
Good morning, here is the log:
Custom_components.mediarr.server.jellyfin Failed to download image backdrop for 443758: 404

The status of the sensor (sensor.seer_mediarr) is set to 1

**Comment by Vansmak** [comment]
I dunno it's really hard for me to know on someone else's system. All 8 can do is make sure it works for me. 

The jellyfin log has nothing to do with seer not setting up. Try just 
```
seer:

    url: http://192.168.254.205:5055

    api_key: !secret seer_api_key//verify
    
    tmdb_api_key: !secret tmdb_api_key
 ```

**Comment by Stefan765** [comment]
Unfortunately, I can't get it to work. Is it possibly because I am using Emby? 
Will you add Emby?
Best regards and thanks for your support

**Comment by Vansmak** [comment]
I dunno it's really hard for me to know on someone else's system. All 8 can do is make sure it works for me. 

The jellyfin log has nothing to do with seer not setting up. Try just 
```
seer:

    url: http://192.168.254.205:5055

    api_key: !secret seer_api_key//verify
    
    tmdb_api_key: !secret tmdb_api_key
 ```
  It's not emby, you said it's jellyseer. Try creating a new key in jellyseer
