### ISSUE TITLE
Plex Recently Added Isn't Updating -- 2.7.1

### ISSUE THREAD

**Issue by iamronr** [Vansmak/mediarr_sensor#7]
I wish I had logs, but I'm not getting any errors. The only bit of logs I could get is from pycache.

![Image](https://github.com/user-attachments/assets/05252357-8009-4db0-b2e3-f82339396c13)

I'm seeing this portion in pycache, which likely means it's not connecting before it gets to that point. Not sure what the setup was when you were storing files locally, but that worked... at least I think it did.

```
   async def _fetch_recently_added(self, section_id):
        """Fetch recently added items from a Plex section."""
        url = f"{self._base_url}/library/sections/{section_id}/recentlyAdded"
        headers = {"X-Plex-Token": self._token}
        try:
            async with async_timeout.timeout(10):
                async with self._session.get(url, headers=headers) as response:
                    if response.status == 200:
                        xml_content = await response.text()
                        return ET.fromstring(xml_content)
                    else:
                        raise Exception(f"Failed to fetch recently added: {response.status}")
        except Exception as err:
            _LOGGER.error("Error fetching recently added: %s", err)
            return None
```

I think I found the Plex issue. I just don't know how to fix it. The issue stems from here:

`url = f"{self._base_url}/library/sections/{section_id}/recentlyAdded"` line 51 in plex.py

I removed the `section_id` and replaced it with a one, it went from this: `url = f"{self._base_url}/library/sections/{section_id}/recentlyAdded"`

![Image](https://github.com/user-attachments/assets/df57a1a2-a0b8-4725-8dd1-aedb05bc289f)

To this: `url = f"{self._base_url}/library/sections/1/recentlyAdded"`

![Image](https://github.com/user-attachments/assets/78cdffdd-b0b0-4c1d-b61e-a83a955d6fe9)

So it works, but whatever is happening, it's not pulling the right sets of section IDs. The poster you see is a movie, but it's showing multiple times.

Nothing has seemed to change much with the URL. I'm no coder, just a tinkerer. Wish I could be of more help.

I'm running everything straight from HACs now, nothing modified.

Here are the plex sensor attributes. It's showing a MasterClass I've added a long time ago. It isn't updating for some reason. 
![Image](https://github.com/user-attachments/assets/7005eeb2-7610-4988-91e7-16fb15b9c0d4)

I deleted pycache and restarted, and get exactly the same logs that's in the screenshot of the initial post. It's not able to connect to plex. I'm unsure why, because nothing has changed with my Plex config.

It’s connecting to my plex media server since it’s pulling content. It’s just not pulling the recently added ones…

Edit: This issue should've been opened up on the sensor GitHub. That's my bad.

I have a question: It wouldn't create the plex sensor if the plex URL and/or token was incorrect right? I was able to test my plex url and token with my old configuration using plex recently added and upcoming media card, and things worked fine there... It's just not as pretty as mediarr-card lol

I understand if it's not finding artwork for that MasterClass. The issue is, I've added loads of content since then. What would keep them from populating? To give context, see the screenshot for when this was actually added:

![Image](https://github.com/user-attachments/assets/792ee116-998a-40cb-9f3a-adbcba16c0c4)

Here's my recently added using Tautulli to give context:

![Image](https://github.com/user-attachments/assets/e7c18550-2833-4b8a-ac23-31a8adbb5243)

I did. I did a fresh install. Wiped cache as well.

Here are the entities in HA
![Image](https://github.com/user-attachments/assets/3dea602b-878d-49c7-81ee-3b87b9e02b4d)

Here are my sensors.yaml
```
- platform: mediarr
    plex:
      host: 192.168.100.65
      port: 32400
      token: !secret plex_token
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key
    
    seer:
      url: http://192.168.100.65:5055
      api_key: !secret jellyseerr_api
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key
    
    sonarr:
      url: http://192.168.100.65:8989
      api_key: !secret sonarr_api
      max_items: 10
      days_to_check: 30
      tmdb_api_key: !secret tmdb_api_long_key
    
    radarr:
      url: http://192.168.100.65:7878
      api_key: !secret radarr_api
      max_items: 10
      tmdb_api_key: !secret tmdb_api_long_key

    trakt:
      client_id: !secret trakt_client_id
      client_secret: !secret trakt_client_secret
      tmdb_api_key: !secret tmdb_api_long_key
      trending_type: both  # Options: movies, shows, both
      max_items: 10

    tmdb:
      tmdb_api_key: !secret tmdb_api_long_key
      trending_type: all  # Options: movie, tv, all
      max_items: 10
      trending: true
      now_playing: true
      upcoming: true
      on_air: true
      airing_today: true
```

The indentation for `- platform: mediarr` is showing off a little bit here...
